### ISSUE TITLE
No response...

### ISSUE THREAD

**Issue by byphone** [ndejong/pfsense_fauxapi#1]
Hi, 

Just test the API against a pfsense 2.3.2-RELEASE-p1 with bash cli.
I obtain the fauxapi-auth, but the curl process gives no response, with no error message.

I setup the package as describe from your github(download package and install it manually).

if i remove the silent option from curl command : 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:39 --:--:--     0

No data is transmitted...

Thanks for your help

**Comment by ndejong** [comment]
Hi - could you provide more detail on the code or command line you are actually running?

**Comment by ndejong** [comment]
Hi - I'm still interested in hearing more about this issue, are you able to share anything?

**Comment by ndejong** [comment]
Closing after no response from original poster - N
