### ISSUE TITLE
Nasty typo in apikey_value generation sample code in README

### ISSUE THREAD

**Issue by mriedmann** [ndejong/pfsense_fauxapi#11]
Took me some time to find the problem:

From README.md:
```
echo PPFA`head /dev/urandom | base64 -w0 | tr -d /+= | head -c 20`
```
Should be:
```
echo PFFA`head /dev/urandom | base64 -w0 | tr -d /+= | head -c 20`
```

**Comment by ndejong** [comment]
Yikes!  documentation errors are the worst.  Thanks a for reporting, docs have been updated and new package has been rolled
