### ISSUE TITLE
Interface down when initially created via FauxAPI

### ISSUE THREAD

**Issue by maesterX** [ndejong/pfsense_fauxapi#2]
When creating an interface with the following JSON:

```{'wan': {'enable': '', 'if': 'igb0', 'descr': 'pfSYNC', 'ipaddr': '<IP>', 'subnet': '30', 'spoofmac': ''}, 'lan': {'enable': '', 'if': 'igb1', 'ipaddr': '<IP>', 'subnet': '24', 'ipaddrv6': '', 'subnetv6': '', 'media': '', 'mediaopt': '', 'track6-interface': 'wan', 'track6-prefix-id': '0', 'gateway': 'GW_LAN', 'gatewayv6': ''}, 'opt1': {'descr': 'WANBOND', 'if': 'lagg0', 'enable': '', 'spoofmac': '', 'mtu': '9000'}, 'opt2': {'descr': 'WAN', 'if': 'lagg0_vlan1112', 'enable': '', 'ipaddr': '<IP>', 'subnet': '29', 'gateway': 'WANv4GW', 'spoofmac': ''}, 'opt3': {'descr': 'VL3301Pub', 'if': 'lagg0_vlan3301', 'spoofmac': '', 'enable': 'True', 'blockpriv': '', 'blockbogons': '', 'ipaddr': '<IP>', 'subnet': '30'}}```

The interfaces appear on the pfSense dashboard as down and doesn't come up unless i disable and re-enable the interface via the GUI. This occurs despite using config.reload().

Is this expected behaviour and if not, can you suggest  a possible cause?

Regards,
Ochuko

**Comment by ndejong** [comment]
Hi 

The configuration you are supplying appears to be an incomplete - you MUST provide a FULL config, not just the parts of the config you wish to set

Have a read over here to understand more about why:-
https://github.com/ndejong/pfsense_fauxapi/issues/3

N

**Comment by phase5** [comment]
Anyone else having this issue, please look at #10.
ndejong provided a solution to a similar issue that I think may have helped here too.
