### ISSUE TITLE
Having FauxAPI Python Library on PyPI?

### ISSUE THREAD

**Issue by fxfitz** [ndejong/pfsense_fauxapi#22]
Have you thought about putting FauxAPI Python Library on PyPI, that way one can just `pip install pfsense_fauxapi` and have all of the dependencies (requests) and library installed super easily?

**Comment by thrawnarn** [comment]
I agree, this would be great... Or at least packaged separatly among releases...

ping @ndejong

**Comment by vwhissell** [comment]
That is indeed a must for this project. Would be amazing to have it installed using pip.
I would love that feature to much. That would make active reponse very easy to block IPs, CnC, bad DNS and stuff.
Make it pip! ;)

**Comment by ssbarnea** [comment]
That is a great idea! Usually there are two things that, most of the time make me decide if I should even bother to test a python library: if it is published to pypi and if it does have a CI running on the repository. Most of the time, if it fails to meet these, i continue browsing.

**Comment by ndejong** [comment]
Took a while, but this is now a thing 
https://github.com/ndejong/pfsense_fauxapi_client_python

Go ahead and install with pip
```
pip3 install pfsense-fauxapi
```
