### ISSUE TITLE
function_call

### ISSUE THREAD

**Issue by furkan92** [ndejong/pfsense_fauxapi#23]
Hello,
i try to take an function_call in bash but i got the error "api action is not defined" ...
i tried as curl call to but its the same error.

any idea?
thanks

**Comment by furkan92** [comment]
i fixed it thanks for no responding ...
the issue was that the function was not exist on the data fauxapi_actions.inc

**Comment by ndejong** [comment]
Thanks @furkan92 - good to hear you were able to resolve on your own - I missed your original issue-report - regards - N

**Comment by ndejong** [comment]
I note that there was a typo in the documentation here, the correct location of the `pfsense_function_calls.txt` file is `/etc/pfsense_function_calls.txt`
