### ISSUE TITLE
How could I reach the DHCP Leases table?

### ISSUE THREAD

**Issue by carldebilly** [ndejong/pfsense_fauxapi#24]
I'm currently trying to build a device presence detection (for integration with SmartThings) and I want to know if a device is present in the DHCP leases table (status="online").

At first it seems it's not available directly in _fauxapi_, but I'm wondering if it's something which can be easily added.

Since I'm definitely not familiar with _PHP_ nor developping for pfSense (I'm a _dotnet_ guy), I don't know where to start to add this in _fauxapi_.

**Comment by carldebilly** [comment]
After few thoughts, I think the _ARP_ table could be a more reliable way to get the presence information I need instead of DHCP.

**Comment by ndejong** [comment]
Based on the detail you've provided "device presence detection" I'd suggest you simply need to watch the ARP tables which can be done at the pfSense console using `arp -a`

Adding a function to provide this would be rather easy but it is a step outside the original mission of providing a programmatic interface to pfSense to manage the `config.xml` file and the functions required to get that config adopted by the system.

This does not mean it's a dead-end, you should be able to use the `function_call` call and invoke the `exec_command` pfSense function to hence make an `arp -a` call and extract the data you need - read-the-docs, you will need to enable `exec_command` in the `/etc/pfsense_function_calls.txt` file to make this work.

Collecting the same data via a simple ssh remote-exec is your other option here.
