### ISSUE TITLE
Quesiton: How to create a user with fauxapi

### ISSUE THREAD

**Issue by Jgerardopine** [ndejong/pfsense_fauxapi#26]
HI,

  I was trying to create a user with fauxapi. From dev shell you can create a new user by running the following command:

```$config['system']['user'][] = <name>```

The only .inc file that makes sense of creatin a user is auth.inc line 480.
I have tried with several functions with the method function_call() from fauxapi, but it doesn't create the user. 
Have you been able to generate a user via fauxapi? I have been trying all day, eventhough the function is passing the arguments properly, and in the debugging is showing but the 200 ok, the user is not being created. Fo you have any clue on how to do this?

Best regards,

Jose Gerardo Pineda

**Comment by ndejong** [comment]
This sounded like a common enough use-case that I created some example code that implements the following:-
 - `get_users` - returns a dict of users on the system
 - `add_user` - adds a new user to the system
 - `manage_user` - manages users attributes such as password, sshkey, description and privileges
 - `remove_user` - removes a user by username
 - `get_groups` - returns a dict of groups on the system
 - `add_group` - creates a new local user group
 - `manage_group` - manages the description, privileges and users in a group
 - `remove_group` - removes a group by group name

You can review the code here:-
https://github.com/ndejong/pfsense_fauxapi/blob/master/extras/examples/usergroup-management.py

The thing to remember is that FauxAPI is a tool for interacting with the pfSense configuration file and as such you sometimes need to do a bit of extra work here and there - in this case we need to increment the `nextuid` and `nextguid` fields after adding users and groups - works just fine though

**Comment by Dev-Romar** [comment]
How to add nat and rules? Im using PHP.

Here is my code for NAT:

    $data = [
        "nat" => [
            "rule" => [
                "source"=>[
                    "any"=>""
                ],
                "destination"=>[
                    "network"=>"wanip",
                    "port"=>"8080"
                ],
                "protocol"=>"tcp",
                "target"=>"192.168.10.300",
                "local-port"=>"5050",
                "interface"=>"wan"
            ]
        ]
    ];

    $response = $client->config_patch($data);
    var_dump($response);
