### ISSUE TITLE
API manage Alias IP

### ISSUE THREAD

**Issue by alebeta90** [ndejong/pfsense_fauxapi#29]
Hello all,

There is a possibility to manage IP Alias, with this API? I saw the option with URL Alias.

thanks

**Comment by ndejong** [comment]
Yes, updating alias tables is a common use case for FauxAPI usage

**Comment by ndejong** [comment]
There is some example code that demonstrates this here:-
https://github.com/ndejong/pfsense_fauxapi/blob/master/extras/examples/update-aws-aliases.py
