### ISSUE TITLE
system_load_config needs to detect proper port for curl exec

### ISSUE THREAD

**Issue by travisghansen** [ndejong/pfsense_fauxapi#31]
Just getting started with this package and noticed it's exec'ing curl like this: curl --silent --insecure \"http:\/\/127.0.0.1\/index.php?__fauxapi_callid=5b8ac08e9846d\

This causes the app to stall for me as I run the webgui on 8080.  If we could make that a bit more dynamic that would be great.  Thanks!

**Comment by ndejong** [comment]
@travisghansen - yes, this is a good suggestion.

The the client libraries also need to be separated into their own repos so they can be made into packages for `pip` and the like.

**Comment by travisghansen** [comment]
I'll be working on a client library (php) tomorrow FYI.  I'll also have an MR for you to fix this issue.

**Comment by travisghansen** [comment]
@ndejong I've opened an MR for this.  Also, I've completed a PHP client: https://github.com/travisghansen/pfsense_fauxapi_php_client

It's available on packagist as well.

**Comment by ndejong** [comment]
Ahh - most excellent, a PHP client, has been a need for this for quite a while - once I break out the Bash and Python clients from this main repo I'll add pointers to your client - thanks again!

**Comment by ndejong** [comment]
Merged pull request: https://github.com/ndejong/pfsense_fauxapi/pull/33
