### ISSUE TITLE
allow /usr/local/pkg as an include dir for function calls

### ISSUE THREAD

**Issue by travisghansen** [ndejong/pfsense_fauxapi#32]
Many addon packages have files in that directory.  It would be helpful to allow included files form that directory as well.

**Comment by ndejong** [comment]
I've taken a look at this and got "something" that probably works at the sacrifice of some stability which itself can be addressed with further effort.

I've taken moment to pause though as I'm not sure I'm comfortable with opening up the universe of possible includes like this - part of the reason the `function_call` is so rigid about what can be included is that I did not want to enable functionality that led to unexpected outcomes ... and it is already in uncharted territory in that regard..

If anyone can describe more reasons why this is an important must-have extension of capability then I'll make it happen.

Will keep this ticket open for the time being.

**Comment by travisghansen** [comment]
@ndejong I'm just using the built-in xmlrpc API now which supports this idea along with anything else so I'm good for now.

**Comment by ndejong** [comment]
That's interesting - could you describe this a little bit more - would it perhaps make sense for FauxAPI to have an xmlrpc endpoint perhaps?

**Comment by travisghansen** [comment]
Basically pfSense has an xmlrpc API that somewhat eliminates the need to use this project.  In my use case, I was developing a piece of software to integrate with pfSense and wanted to make the 'barrier to entry' as low as possible.  Requiring users to install/setup the fauxapi in conjunction with the limitation(s) originally mentioned on this ticket were factors in directly using the built-in xmlrpc api (I was unaware of the extent of features it offered...which is basically anything you need/want and more).

None of this is meant to demean this project FYI.  Just stuff I discovered along the way.

- https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/xmlrpc.php
- https://github.com/travisghansen/kubernetes-pfsense-controller

**Comment by ndejong** [comment]
Ahh - that's awesome, certainly do like your kubernetes-pfsense-controller too - dare I say it, did you consider using OPNsense rather than pfSense for this though?  I've been doing a lot more with OPNsense of late (https://github.com/verbnetworks) and find the OPNsense code _much_ cleaner etc.

**Comment by travisghansen** [comment]
@ndejong I've used pfsense for a long time and didn't follow the IMO petty banter between the 2 projects (from both sides from what I can tell).

Perhaps in the future I'll take a look but I've been running the installations I have in production for many years and didn't want to mess with those installs.

Having said that, I have nothing against the newer project and my controller could pretty easily be adapted to opnsense if the API supports all needed functions.

I have plans to tie into fail2ban (with kubernetes logs) but instead of making iptables call it would make rules in pfsense.  Kinda lofty goal but doable :)

**Comment by nasirhafeez** [comment]
Hi,

A possible use case that I've encountered for this: I'm trying to automate some SquidGuard functions, and SquidGuard requires the Apply button in General Settings to be pressed after making changes.

![image](https://user-images.githubusercontent.com/38311694/101870911-5d3ebc80-3ba4-11eb-89fb-f479d8399bbd.png)

This runs the `sg_reconfigure()` function from `/usr/local/pkg/squidguard.inc` in the background. If FauxAPI were to support included files from `/usr/local/pkg` directory then one could use `function_call` to execute `sg_reconfigure()` via FauxAPI.

Other than that, I don't see how one could do this via FauxAPI.
