### ISSUE TITLE
Function_Call portal_allow

### ISSUE THREAD

**Issue by cappe87** [ndejong/pfsense_fauxapi#39]
Hi everybody!
I would like to compliment you greatly on your work.

I'm trying to authenticate users on the captive portal using function_call with portal_allow function.
Unfortunately it doesn't works.

I think the problem is the cpzone, with portal_allow called by the API PfSense doesn't recognize in which zone I want to authenticate the user.

Is there anybody who can help me?

**Comment by ndejong** [comment]
@cappe87 - did you manage to figure out a solution to your requirement here?

**Comment by cappe87** [comment]
Hello,
sorry, I don't have a solution
