### ISSUE TITLE
consider marking the library an ansible module

### ISSUE THREAD

**Issue by ssbarnea** [ndejong/pfsense_fauxapi#41]
I would argue that marking the library usable as an ansible module would make it even more valuable for configuration management.

**Comment by ndejong** [comment]
Thanks for the suggestion - could you describe how you'd see that working in a little more detail?

**Comment by ndejong** [comment]
An existing Ansible module exists, have reached out to that project to figure out if there is something to work on together - https://github.com/opoplawski/ansible-pfsense/issues/12
