### ISSUE TITLE
NodeJS/TypeScript Client Library

### ISSUE THREAD

**Issue by ancientwinds** [ndejong/pfsense_fauxapi#43]
Hi, We wrote a client sdk in nodejs/typescript for the FauxAPI. You can find it [here](https://www.npmjs.com/package/faux-api-client). Would it be a good thing to include the library in your project? If so, is a pull request the best approach for that?

**Comment by ndejong** [comment]
This is awesome.

I've been putting off the task of splitting out the various client implementations for long enough and this one is yet another one - if you can stall for a few weeks I'll get you to make a pull request for a new client repo to handle this.

Thanks

**Comment by ndejong** [comment]
I've added references to your library to the main documentation - thanks for the awesome contribution!
