### ISSUE TITLE
Add parameter to PfsenseFauxapi() to specify http/https port

### ISSUE THREAD

**Issue by nomodz4real** [ndejong/pfsense_fauxapi#49]
Please add argument to class FauxAPIPy: to allow users to specify the port that pfsense is listening on for http and https traffic.

**Comment by ndejong** [comment]
Refer to https://github.com/ndejong/pfsense_fauxapi/issues/48#issuecomment-497995906 for the time being - waiting feedback

**Comment by nomodz4real** [comment]
As was referred to in #48 this can be done so I am closing this issue. Apologies for being "overeager" on this one.
