### ISSUE TITLE
APIKEY and APIKEYSECRET confusion

### ISSUE THREAD

**Issue by masifpak** [ndejong/pfsense_fauxapi#5]
I am unable to understand these two terms. in first apikey is being used while taking taking hash apisecret is being used.

> fauxapi-auth: <apikey>:<timestamp>:<nonce>:<hash>
> <hash> = sha256(<apisecret><timestamp><nonce>)

What if i use below as it is. I use it, it gives no error. 

> curl \
>         -X GET \
>         --silent \
>         --insecure \
>         --header "fauxapi-auth: PFFA4797d073:20161119Z144328:833a45d8:9c4f96ab042f5140386178618be1ae40adc68dd9fd6b158fb82c99f3aaa2bb55" \
>         "https://192.168.10.10/fauxapi/v1/?action=config_get"

**Comment by ndejong** [comment]
Hi Masifpak,

Your question is not entirely clear to me, I'll attempt to answer as best I can, perhaps you could ask again with more description on what you are having trouble with.

<apikey> = the identifier of the API key, this is simply an reference value there is nothing secret about it
<apisecret> = the secret value associated with the <apikey> keep this value private, also, in order to prevent poor choices there are (pedantic) rules around what values are valid here, have a read in the provided sample credentials file `/etc/fauxapi/credentials.ini` 

NB: you MUST set your own <apikey> and <apisecret> value before you'll be able to use the fauxapi.

Also, try adding `__debug=true` to the end of your curl request to obtain extra debug information that should help you in determining where the problem is - your request URL would hence become:-
```
https://192.168.10.10/fauxapi/v1/?action=config_get&__debug=true
```

**Comment by masifpak** [comment]
Here is my credential.ini file. How can this help me in 
curl  -X GET --silent --insecure --header "fauxapi-auth: PFFA4797d073:20161119Z144328:833a45d8:9c4f96ab042f5140386178618be1ae40adc68dd9fd6b158fb82c99f3aaa2bb55" "https://192.168.10.10/fauxapi/v1/?action=config_get" 
I have also tried `&_debug=true`  but nothing happen. Just execute the command without any output or error. 

> [PFFAexample01]
> secret = abcdefghijklmnopqrstuvwxyz0123456789abcd
> owner = Example01 Firstname Lastname
> [PFFAexample02]
> secret = ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCD
> owner = Example02 Firstname Lastname

**Comment by masifpak** [comment]
I have also tried like this.

![image](https://cloud.githubusercontent.com/assets/12061167/26144581/d278a890-3b02-11e7-9cde-11ebde0d7d69.png)

**Comment by masifpak** [comment]
In below, i am using random apikey and apisecret and facing the following problem
![image](https://cloud.githubusercontent.com/assets/12061167/26151443/5f823cf6-3b1c-11e7-9c13-0bb7c1475e06.png)

**Comment by masifpak** [comment]
What is the purpose of Owner. Can i use these same apikey and apisecret?

**Comment by phase5** [comment]
Hi Masifpak,

Based on the credential.ini you posted above, could I point you to the following sentence from the documentation: -

> The two sample FauxAPI keys (PFFAexample01 and PFFAexample02) and their associated secrets in the sample credentials.ini file are hard-coded to be inoperative, you must create entirely new values before your client scripts will be able to issue commands to FauxAPI.

Before anything else, you need to add your own credential.  for example: -

```
[PFFAmasifpak1]
secret = abcdefghijklmnopqrstuvwxyz0123456789abcd
owner = Hello my name is masifpak
```

As far as I am aware, the owner field is purely for display purposes. (I think it is like a comment)

Hope that is of some use.

**Comment by ndejong** [comment]
Hi Masifpak,

I've updated the documentation and provided an easy command line example to automatically generate credentials that will be valid:-

#### apikey_value
```bash
$ echo PPFA`head /dev/urandom | base64 -w0 | tr -d /+= | head -c 20`
```

#### apisecret_value
```bash
$ echo `head /dev/urandom | base64 -w0 | tr -d /+= | head -c 60`
```

Hope that clears things up for you

**Comment by fahadalishah5** [comment]
Hi, 
I am facing some confusion regarding this play how to create API string i am trying to sync this firewall with 3rd party tool. 

Here is my Credentials. ini file config. 

;; PFFAexample01 is hardcoded to be inoperative
[PFFAfahad09800552]
secret = 8897562242abcdefghijklmnopqrtsuvwxyz09812345
permit = alias_*, config_*, gateway_*, rule_*, send_*, system_*, function_*
comment = PFFAfahad09800552 - hardcoded to be inoperative

How i can check this one working? What is the roll of Python in it? What next configuration i need to do after this? How this API string create in below format?

fauxapi-auth: PFFA4797d073:20161119Z144328:833a45d8:9c4f96ab042f5140386178618be1ae40adc68dd9fd6b158fb82c99f3aaa2bb55

Is this example Auth ??
