### ISSUE TITLE
Using Postman to read/write to PFSense API - Authentication Failed

### ISSUE THREAD

**Issue by marcusdandrea** [ndejong/pfsense_fauxapi#6]
I'm using PFSense 2.3.4 with the latest FauxAPI and have setup my crenditials.ini with the correct information.   However, my authentication keeps telling me I have an invalid hash from the debug's and Postman but it should be valid. 

Thanks.

**Comment by rdgerken** [comment]
Hi, I'm using PFSense 2.3.4 also, and having the same issue.  I can't get anything to work, I just get "authentication failed" messages.  What code does the package use to generate the timestamp?  I would like to verify that my client and pfsense hosts are returning matching timestamps.  I'm using the Python code you provided, so I see what the client is doing.

**Comment by rdgerken** [comment]
Well, it's definitely not a timestamp issue.  I've confirmed the Python client library is generating the exact same timestamp as my pfsense box.  (Within a few seconds of each other)

**Comment by rdgerken** [comment]
OK, I got it to work finally... didn't RTFM - my key length was too short.

**Comment by marcusdandrea** [comment]
Yeah python and bash work fine for me just postman that does not.

**Comment by ndejong** [comment]
Happy to hear you managed to sort out your issues there - there have been enough comments with others getting getting stuck that it probably makes sense to roll a feature into the UI to auto-generate them - I'll add this to the next release - N
