### ISSUE TITLE
intergration into Pfsense 2.5

### ISSUE THREAD

**Issue by NorthernMunkey** [ndejong/pfsense_fauxapi#61]
i know not necessarily a fault but i'm sure like most they would love to see this implemented into the latest version of pfsense.

i did attempt it and on the whole it looks ok
installs ok
showing in pfsense gui
just an error about a directory not available in line 38 of a configuration file

not being an expert but it doesn't sound like a massive issue
could it be looked at maybe?

I, like allot would be very grateful

**Comment by oasisck** [comment]
Following
Waiting for your confirmation that's everything is ok before upgrading pfsense

**Comment by ndejong** [comment]
Yep - waiting for 2.5 series to be released, right now the latest release version appears to be 2.4.5 
* https://www.pfsense.org/download/
* https://www.pfsense.org/snapshots/

**Comment by ndejong** [comment]
Done - tested against the current 2.5.x DEVELOPMENT iso image `pfSense-CE-2.5.0-DEVELOPMENT-amd64-20200527-1410.iso`
