### ISSUE TITLE
Question : system_stats > cpu value ?

### ISSUE THREAD

**Issue by oasisck** [ndejong/pfsense_fauxapi#62]
Hello, I just wanna know what values report "cpu" in system_stats
```
{
  "callid": "5b3b511655589",
  "action": "system_stats",
  "message": "ok",
  "data": {
    "stats": {
      "cpu": "20770421|20494981",
```
Thanks for your wonderful API

**Comment by ndejong** [comment]
Good question, this comes from the pfSense `cpu_usage()` function itself that you can see here:- 
https://github.com/pfsense/pfsense/blob/master/src/usr/local/www/includes/functions.inc.php#L84

The comment there states:-
"""
Returns the current total ticks and user ticks. The dashboard widget calculates the load from that
"""

Reading the pfSense code is seems that the first value is the sum of the CPU usage and the second value is the CPU idle time
