### ISSUE TITLE
HA Sync after update config

### ISSUE THREAD

**Issue by jansinkeNL** [ndejong/pfsense_fauxapi#63]
I am using PFsense 2.4.5 and FAUXApi to automatic update some firewallrules. It works great. But in my situation we have a HA configuration. Normaly when i update Firewall1, Firewall2 is automatic updatet as wel. But when i use FAUXApi this is not the case. Am i doing something wrong ?
Thanks for your help

**Comment by ndejong** [comment]
Try doing a `send_event` with `filter sync` after the update to firewall rules 
https://github.com/ndejong/pfsense_fauxapi#send_event

Please do let us know how it goes

**Comment by jansinkeNL** [comment]
It works, thanks a lot!!

After the config_path, i send "filter sync" event and a couple of seconds later, the second firewall had the updated filter rules.
