### ISSUE TITLE
Uninstall Instructions?

### ISSUE THREAD

**Issue by rdgerken** [ndejong/pfsense_fauxapi#7]
Could you please provide uninstall instructions please?  I didn't see them anywhere, and it's not showing up in the package manager.

Thanks!

**Comment by ndejong** [comment]
Yes, this is a reasonable request - I'll add that as a feature in a newer release - N

**Comment by ndejong** [comment]
Instructions added, it's a simple one-liner  `pkg delete pfSense-pkg-FauxAPI`
