### ISSUE TITLE
Example to add new users and move to member groups

### ISSUE THREAD

**Issue by KelvinFerraz** [ndejong/pfsense_fauxapi#72]
Hello,

First one i need say thank you, your API is amazing!

So i have a little problem to understand how to add a new user using python

I'm read your documentation : https://github.com/ndejong/pfsense_fauxapi_client_python/blob/master/examples/usergroup-management.py

But i'm don't understoood complete, you have a simple example how to add user and move this user to expecific group?

Best,

**Comment by ndejong** [comment]
Hi

Thanks for getting in content - the Python client example does exactly that -
https://github.com/ndejong/pfsense_fauxapi_client_python/blob/master/examples/usergroup-management.py

* create a new user - [here](https://github.com/ndejong/pfsense_fauxapi_client_python/blob/8e706e275232ef0ffd753fda16887299d5092ead/examples/usergroup-management.py#L333)
* modify some user attributes - [here](https://github.com/ndejong/pfsense_fauxapi_client_python/blob/8e706e275232ef0ffd753fda16887299d5092ead/examples/usergroup-management.py#L345)
* create a new group - [here](https://github.com/ndejong/pfsense_fauxapi_client_python/blob/8e706e275232ef0ffd753fda16887299d5092ead/examples/usergroup-management.py#L351)
* add the new user to the new group - [here](https://github.com/ndejong/pfsense_fauxapi_client_python/blob/8e706e275232ef0ffd753fda16887299d5092ead/examples/usergroup-management.py#L360)
* remove the group - [here](https://github.com/ndejong/pfsense_fauxapi_client_python/blob/8e706e275232ef0ffd753fda16887299d5092ead/examples/usergroup-management.py#L366)
* remove the user - [here](https://github.com/ndejong/pfsense_fauxapi_client_python/blob/8e706e275232ef0ffd753fda16887299d5092ead/examples/usergroup-management.py#L370)

The `UserGroupManagementFauxapi` class in the example provided above does the grunt work of things like `add_user()` and `manage_user()` and `add_group()` and `manage_group()` etc ...

Hope that helps.
