### ISSUE TITLE
make firewall rule with python fauxapi

### ISSUE THREAD

**Issue by kevin-fontys** [ndejong/pfsense_fauxapi#73]
hey,

I'm trying to add a firewall rule with the help of the fauxapi API via python but i can't seem to find an example of how to do it.
i read in another issue that you needed to export the entire config, edit it and then upload the entire config back to pfsense. 
however i have no idea what to edit or where to put the new rule. is it possible to you to make an example of how to add a rule via this methode? -Kevin

**Comment by CloudAc** [comment]
Just create an example firewall rule and request the config data with config_get.
Then you can inspect how this rule has been setup.

**Comment by ndejong** [comment]
Agreed - this would make a good Python client example to add to the collection here -
* https://github.com/ndejong/pfsense_fauxapi_client_python/tree/master/examples

Closing this ticket and adding the idea-for-example to the `pfsense_fauxapi_client_python` repo
