### ISSUE TITLE
fetch : bad request

### ISSUE THREAD

**Issue by FplusOlivier** [ndejong/pfsense_fauxapi#77]
Hello,
On pfsense 2.5.0, when trying to fetch ${fauxapi_base_package_url}/${fauxapi_latest}
Result is :
fetch: https://raw.githubusercontent.com/ndejong/pfsense_fauxapi_packages/master/: Bad Request

Thanks

**Comment by ndejong** [comment]
Hi -

Before you can do a `fetch ${fauxapi_base_package_url}/${fauxapi_latest}` you'll need to set those two environment variables like this:- 
```bash
set fauxapi_base_package_url='https://raw.githubusercontent.com/ndejong/pfsense_fauxapi_packages/master'
set fauxapi_latest=`fetch -qo - ${fauxapi_base_package_url}/LATEST`
```

You really should be able to cut-n-paste the whole example [here](https://github.com/ndejong/pfsense_fauxapi#installation)

Closing this for now, please re-open if this is still a problem for you
