### ISSUE TITLE
Set Firewall Rule?

### ISSUE THREAD

**Issue by rdgerken** [ndejong/pfsense_fauxapi#8]
Sorry for opening these issues... wasn't sure how else to communicate.  I'm developing an EventGhost plugin using your fauxapi library provided here.  I really need to be able to set firewall rules (such as enable/disable existing rules) much like you do when you get the rules providing the rule number.  Do you know if this is possible?  This would be so very helpful!  I understand you could pull/modify/restore the entire configuration, and then reboot - but I need something much quicker - like set the rule, then do a filter reload kind of thing.  TIA

**Comment by ndejong** [comment]
Hi - yes you can certainly add/remove rules to a running box without rebooting - I suspect the biggest issue is going to be that you must  retrieve the _entire_ pfSense configuration, modify the rules and then then return the entire pfSense configuration again - I know this is less than ideal however it's a limitation of the underlying way that pfSense is put together without a clear control layer to interface with - N
