### ISSUE TITLE
apikey_value generation

### ISSUE THREAD

**Issue by ahmaddxb** [ndejong/pfsense_fauxapi#81]
When I use the command echo PFFA`head /dev/urandom | base64 -w0 | tr -d /+= | head -c 20` or echo `head /dev/urandom | base64 -w0 | tr -d /+= | head -c 60`

i get this
base64: Command not found.

**Comment by dunderrrrrr** [comment]
You need coreutils. 
```sudo apt install coreutils```

**Comment by ahmaddxb** [comment]
now
sudo: Command not found.

**Comment by dunderrrrrr** [comment]
What linux dist are you running?

**Comment by ahmaddxb** [comment]
this is pfsense freebsd

**Comment by dunderrrrrr** [comment]
Oh youre running it in the box, i see. 

Try this, ```pkg install base64```.

**Comment by ahmaddxb** [comment]
pkg install base64 doesnt work package not found

I run the command on another linux manchine now and they worked so I guess that good enought.

Thanks

**Comment by dunderrrrrr** [comment]
Okay, yeah ive always been running the command on another ubuntu-machine. 

Glad to hear you worked it out.
